# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Henry's Blog
tagline:          ''
description:      'hello world!'
url:              https://github.com/rwggad/

baseurl:          /developer_page   # gitpage
#baseurl:          # local test

author:
  name:           'Jeonghwan Kim'
  url:            ''

paginate:         2

# Custom vars
version:          0.0.1a

github:
  repo:           https://github.com/rwggad/developer_page

plugins:          [jekyll-paginate]
